# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaedc62c90fb8e64e99d5d82bceebd386500754e59ace1c292abc40c91847198379bf7124d48e09f80a43e37ee3090511b0681614414f8310d612367fcdd8794

test:
  secret_key_base: eab257edcbf48ac68372a01e9a8dcb13b188b3b81fa5bc840330a7daa4bd425721e4e56a7bff1a8ef60258952c7d15b22cc1548a27aef0a2458b9c4d189f8fe8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
